-- ============================================================
-- App 内 APK 更新：原生壳版本表 app_native_versions
-- 执行位置：Supabase Dashboard → SQL Editor → 全选粘贴 → Run
-- 幂等：可重复执行不出错（IF NOT EXISTS / DROP POLICY IF EXISTS）
--
-- 作用：存放 APK 发布记录（版本号/下载路径/SHA256/更新说明），
--       App 冷启动时查询此表判断是否有新壳版本可更新。
-- 不执行的影响：App 查询报错但静默降级（不影响使用），
--       只是无法收到"App 内更新 APK"的提示。
-- ============================================================

create table if not exists public.app_native_versions (
  id bigint generated by default as identity primary key,
  -- 壳版本号（语义化，与 build.gradle 的 versionName 一致，如 2.1.0）
  version_name text not null unique,
  -- 内部版本号（与 build.gradle 的 versionCode 一致，单调递增）
  version_code integer not null,
  -- APK 在 app_updates bucket 里的存储路径（如 apks/youai-2.1.0.apk）
  storage_path text not null,
  -- APK 文件字节数（面板展示体积用）
  apk_size_bytes bigint,
  -- APK 的 SHA-256（客户端下载后校验，防坏包/防篡改）
  apk_sha256 text,
  -- 更新说明（面板展示改了什么）
  notes text,
  enabled boolean not null default true,
  released_at timestamptz not null default now()
);

-- 行级安全：写入仅 service_role（发布脚本用，绕过 RLS，无需额外 policy）；
-- 登录用户只读。
alter table public.app_native_versions enable row level security;

drop policy if exists "authenticated read app_native_versions"
  on public.app_native_versions;
create policy "authenticated read app_native_versions"
  on public.app_native_versions
  for select
  to authenticated
  using (true);

-- 索引：客户端按 enabled + released_at 查最新一条
create index if not exists idx_app_native_versions_latest
  on public.app_native_versions (enabled, released_at desc);
